project:
  type: website
  output-dir: docs

website:
  title: "Zachary Palmore"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



